// Generated by gir (https://github.com/gtk-rs/gir @ 81e2ef9e1ab7)
// from ../../gir-files (@ 3b6fe0a33676)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GeditApp", sizeof(GeditApp), alignof(GeditApp));
    printf("%s;%zu;%zu\n", "GeditAppActivatableInterface", sizeof(GeditAppActivatableInterface), alignof(GeditAppActivatableInterface));
    printf("%s;%zu;%zu\n", "GeditAppClass", sizeof(GeditAppClass), alignof(GeditAppClass));
    printf("%s;%zu;%zu\n", "GeditDebugSection", sizeof(GeditDebugSection), alignof(GeditDebugSection));
    printf("%s;%zu;%zu\n", "GeditDocument", sizeof(GeditDocument), alignof(GeditDocument));
    printf("%s;%zu;%zu\n", "GeditDocumentClass", sizeof(GeditDocumentClass), alignof(GeditDocumentClass));
    printf("%s;%zu;%zu\n", "GeditEncodingsComboBoxClass", sizeof(GeditEncodingsComboBoxClass), alignof(GeditEncodingsComboBoxClass));
    printf("%s;%zu;%zu\n", "GeditMenuExtensionClass", sizeof(GeditMenuExtensionClass), alignof(GeditMenuExtensionClass));
    printf("%s;%zu;%zu\n", "GeditMessage", sizeof(GeditMessage), alignof(GeditMessage));
    printf("%s;%zu;%zu\n", "GeditMessageBus", sizeof(GeditMessageBus), alignof(GeditMessageBus));
    printf("%s;%zu;%zu\n", "GeditMessageBusClass", sizeof(GeditMessageBusClass), alignof(GeditMessageBusClass));
    printf("%s;%zu;%zu\n", "GeditMessageClass", sizeof(GeditMessageClass), alignof(GeditMessageClass));
    printf("%s;%zu;%zu\n", "GeditProgressInfoBarClass", sizeof(GeditProgressInfoBarClass), alignof(GeditProgressInfoBarClass));
    printf("%s;%zu;%zu\n", "GeditStatusbarClass", sizeof(GeditStatusbarClass), alignof(GeditStatusbarClass));
    printf("%s;%zu;%zu\n", "GeditTabClass", sizeof(GeditTabClass), alignof(GeditTabClass));
    printf("%s;%zu;%zu\n", "GeditTabState", sizeof(GeditTabState), alignof(GeditTabState));
    printf("%s;%zu;%zu\n", "GeditView", sizeof(GeditView), alignof(GeditView));
    printf("%s;%zu;%zu\n", "GeditViewActivatableInterface", sizeof(GeditViewActivatableInterface), alignof(GeditViewActivatableInterface));
    printf("%s;%zu;%zu\n", "GeditViewClass", sizeof(GeditViewClass), alignof(GeditViewClass));
    printf("%s;%zu;%zu\n", "GeditWindow", sizeof(GeditWindow), alignof(GeditWindow));
    printf("%s;%zu;%zu\n", "GeditWindowActivatableInterface", sizeof(GeditWindowActivatableInterface), alignof(GeditWindowActivatableInterface));
    printf("%s;%zu;%zu\n", "GeditWindowClass", sizeof(GeditWindowClass), alignof(GeditWindowClass));
    printf("%s;%zu;%zu\n", "GeditWindowState", sizeof(GeditWindowState), alignof(GeditWindowState));
    return 0;
}
