// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::View;
use glib::object::IsA;
use glib::translate::*;
use glib::StaticType;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "GeditViewActivatable")]
    pub struct ViewActivatable(Interface<ffi::GeditViewActivatable, ffi::GeditViewActivatableInterface>);

    match fn {
        type_ => || ffi::gedit_view_activatable_get_type(),
    }
}

impl ViewActivatable {
        pub const NONE: Option<&'static ViewActivatable> = None;
    
}

pub trait ViewActivatableExt: 'static {
    #[doc(alias = "gedit_view_activatable_activate")]
    fn activate(&self);

    #[doc(alias = "gedit_view_activatable_deactivate")]
    fn deactivate(&self);

    fn view(&self) -> Option<View>;
}

impl<O: IsA<ViewActivatable>> ViewActivatableExt for O {
    fn activate(&self) {
        unsafe {
            ffi::gedit_view_activatable_activate(self.as_ref().to_glib_none().0);
        }
    }

    fn deactivate(&self) {
        unsafe {
            ffi::gedit_view_activatable_deactivate(self.as_ref().to_glib_none().0);
        }
    }

    fn view(&self) -> Option<View> {
        glib::ObjectExt::property(self.as_ref(), "view")
    }
}

impl fmt::Display for ViewActivatable {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("ViewActivatable")
    }
}
