// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../gir-files
// DO NOT EDIT

use crate::Document;
use crate::MessageBus;
use crate::Tab;
use crate::View;
use crate::WindowState;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use glib::StaticType;
use glib::ToValue;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    #[doc(alias = "GeditWindow")]
    pub struct Window(Object<ffi::GeditWindow, ffi::GeditWindowClass>) @extends gtk::ApplicationWindow, gtk::Window, gtk::Bin, gtk::Container, gtk::Widget;

    match fn {
        type_ => || ffi::gedit_window_get_type(),
    }
}

impl Window {
        pub const NONE: Option<&'static Window> = None;
    

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`Window`] objects.
            ///
            /// This method returns an instance of [`WindowBuilder`](crate::builders::WindowBuilder) which can be used to create [`Window`] objects.
            pub fn builder() -> WindowBuilder {
                WindowBuilder::default()
            }
        
}

#[derive(Clone, Default)]
// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`Window`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct WindowBuilder {
    show_menubar: Option<bool>,
    #[cfg(any(feature = "gtk_v2_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_4")))]
    accept_focus: Option<bool>,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    application: Option<gtk::Application>,
    #[cfg(any(feature = "gtk_v3_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_4")))]
    attached_to: Option<gtk::Widget>,
    #[cfg(any(feature = "gtk_v2_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_4")))]
    decorated: Option<bool>,
    default_height: Option<i32>,
    default_width: Option<i32>,
    #[cfg(any(feature = "gtk_v2_10", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_10")))]
    deletable: Option<bool>,
    destroy_with_parent: Option<bool>,
    #[cfg(any(feature = "gtk_v2_6", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_6")))]
    focus_on_map: Option<bool>,
    #[cfg(any(feature = "gtk_v2_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_20")))]
    focus_visible: Option<bool>,
    //gravity: /*Unknown type*/,
    #[cfg(any(feature = "gtk_v3_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_4")))]
    hide_titlebar_when_maximized: Option<bool>,
    //icon: /*Unknown type*/,
    #[cfg(any(feature = "gtk_v2_6", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_6")))]
    icon_name: Option<String>,
    #[cfg(any(feature = "gtk_v2_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_20")))]
    mnemonics_visible: Option<bool>,
    modal: Option<bool>,
    resizable: Option<bool>,
    role: Option<String>,
    screen: Option<gdk::Screen>,
    skip_pager_hint: Option<bool>,
    skip_taskbar_hint: Option<bool>,
    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    startup_id: Option<String>,
    title: Option<String>,
    #[cfg(any(feature = "gtk_v2_10", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_10")))]
    transient_for: Option<gtk::Window>,
    //type: /*Unknown type*/,
    //type-hint: /*Unknown type*/,
    urgency_hint: Option<bool>,
    //window-position: /*Unknown type*/,
    border_width: Option<u32>,
    child: Option<gtk::Widget>,
    //resize-mode: /*Unknown type*/,
    app_paintable: Option<bool>,
    can_default: Option<bool>,
    can_focus: Option<bool>,
    //events: /*Unknown type*/,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    expand: Option<bool>,
    #[cfg(any(feature = "gtk_v3_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_20")))]
    focus_on_click: Option<bool>,
    //halign: /*Unknown type*/,
    has_default: Option<bool>,
    has_focus: Option<bool>,
    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    has_tooltip: Option<bool>,
    height_request: Option<i32>,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    hexpand: Option<bool>,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    hexpand_set: Option<bool>,
    is_focus: Option<bool>,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    margin: Option<i32>,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    margin_bottom: Option<i32>,
    #[cfg(any(feature = "gtk_v3_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_12")))]
    margin_end: Option<i32>,
    #[cfg(any(feature = "gtk_v3_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_12")))]
    margin_start: Option<i32>,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    margin_top: Option<i32>,
    name: Option<String>,
    no_show_all: Option<bool>,
    #[cfg(any(feature = "gtk_v3_8", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_8")))]
    opacity: Option<f64>,
    parent: Option<gtk::Container>,
    receives_default: Option<bool>,
    sensitive: Option<bool>,
    //style: /*Unknown type*/,
    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    tooltip_markup: Option<String>,
    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    tooltip_text: Option<String>,
    //valign: /*Unknown type*/,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    vexpand: Option<bool>,
    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    vexpand_set: Option<bool>,
    visible: Option<bool>,
    width_request: Option<i32>,
}

impl WindowBuilder {
    // rustdoc-stripper-ignore-next
    /// Create a new [`WindowBuilder`].
    pub fn new() -> Self {
        Self::default()
    }


    // rustdoc-stripper-ignore-next
    /// Build the [`Window`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Window {
        let mut properties: Vec<(&str, &dyn ToValue)> = vec![];
if let Some(ref show_menubar) = self.show_menubar {
                properties.push(("show-menubar", show_menubar));
            }
        #[cfg(any(feature = "gtk_v2_4", feature = "dox"))]
if let Some(ref accept_focus) = self.accept_focus {
                properties.push(("accept-focus", accept_focus));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref application) = self.application {
                properties.push(("application", application));
            }
        #[cfg(any(feature = "gtk_v3_4", feature = "dox"))]
if let Some(ref attached_to) = self.attached_to {
                properties.push(("attached-to", attached_to));
            }
        #[cfg(any(feature = "gtk_v2_4", feature = "dox"))]
if let Some(ref decorated) = self.decorated {
                properties.push(("decorated", decorated));
            }
if let Some(ref default_height) = self.default_height {
                properties.push(("default-height", default_height));
            }
if let Some(ref default_width) = self.default_width {
                properties.push(("default-width", default_width));
            }
        #[cfg(any(feature = "gtk_v2_10", feature = "dox"))]
if let Some(ref deletable) = self.deletable {
                properties.push(("deletable", deletable));
            }
if let Some(ref destroy_with_parent) = self.destroy_with_parent {
                properties.push(("destroy-with-parent", destroy_with_parent));
            }
        #[cfg(any(feature = "gtk_v2_6", feature = "dox"))]
if let Some(ref focus_on_map) = self.focus_on_map {
                properties.push(("focus-on-map", focus_on_map));
            }
        #[cfg(any(feature = "gtk_v2_20", feature = "dox"))]
if let Some(ref focus_visible) = self.focus_visible {
                properties.push(("focus-visible", focus_visible));
            }
        #[cfg(any(feature = "gtk_v3_4", feature = "dox"))]
if let Some(ref hide_titlebar_when_maximized) = self.hide_titlebar_when_maximized {
                properties.push(("hide-titlebar-when-maximized", hide_titlebar_when_maximized));
            }
        #[cfg(any(feature = "gtk_v2_6", feature = "dox"))]
if let Some(ref icon_name) = self.icon_name {
                properties.push(("icon-name", icon_name));
            }
        #[cfg(any(feature = "gtk_v2_20", feature = "dox"))]
if let Some(ref mnemonics_visible) = self.mnemonics_visible {
                properties.push(("mnemonics-visible", mnemonics_visible));
            }
if let Some(ref modal) = self.modal {
                properties.push(("modal", modal));
            }
if let Some(ref resizable) = self.resizable {
                properties.push(("resizable", resizable));
            }
if let Some(ref role) = self.role {
                properties.push(("role", role));
            }
if let Some(ref screen) = self.screen {
                properties.push(("screen", screen));
            }
if let Some(ref skip_pager_hint) = self.skip_pager_hint {
                properties.push(("skip-pager-hint", skip_pager_hint));
            }
if let Some(ref skip_taskbar_hint) = self.skip_taskbar_hint {
                properties.push(("skip-taskbar-hint", skip_taskbar_hint));
            }
        #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
if let Some(ref startup_id) = self.startup_id {
                properties.push(("startup-id", startup_id));
            }
if let Some(ref title) = self.title {
                properties.push(("title", title));
            }
        #[cfg(any(feature = "gtk_v2_10", feature = "dox"))]
if let Some(ref transient_for) = self.transient_for {
                properties.push(("transient-for", transient_for));
            }
if let Some(ref urgency_hint) = self.urgency_hint {
                properties.push(("urgency-hint", urgency_hint));
            }
if let Some(ref border_width) = self.border_width {
                properties.push(("border-width", border_width));
            }
if let Some(ref child) = self.child {
                properties.push(("child", child));
            }
if let Some(ref app_paintable) = self.app_paintable {
                properties.push(("app-paintable", app_paintable));
            }
if let Some(ref can_default) = self.can_default {
                properties.push(("can-default", can_default));
            }
if let Some(ref can_focus) = self.can_focus {
                properties.push(("can-focus", can_focus));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref expand) = self.expand {
                properties.push(("expand", expand));
            }
        #[cfg(any(feature = "gtk_v3_20", feature = "dox"))]
if let Some(ref focus_on_click) = self.focus_on_click {
                properties.push(("focus-on-click", focus_on_click));
            }
if let Some(ref has_default) = self.has_default {
                properties.push(("has-default", has_default));
            }
if let Some(ref has_focus) = self.has_focus {
                properties.push(("has-focus", has_focus));
            }
        #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
if let Some(ref has_tooltip) = self.has_tooltip {
                properties.push(("has-tooltip", has_tooltip));
            }
if let Some(ref height_request) = self.height_request {
                properties.push(("height-request", height_request));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref hexpand) = self.hexpand {
                properties.push(("hexpand", hexpand));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref hexpand_set) = self.hexpand_set {
                properties.push(("hexpand-set", hexpand_set));
            }
if let Some(ref is_focus) = self.is_focus {
                properties.push(("is-focus", is_focus));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref margin) = self.margin {
                properties.push(("margin", margin));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref margin_bottom) = self.margin_bottom {
                properties.push(("margin-bottom", margin_bottom));
            }
        #[cfg(any(feature = "gtk_v3_12", feature = "dox"))]
if let Some(ref margin_end) = self.margin_end {
                properties.push(("margin-end", margin_end));
            }
        #[cfg(any(feature = "gtk_v3_12", feature = "dox"))]
if let Some(ref margin_start) = self.margin_start {
                properties.push(("margin-start", margin_start));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref margin_top) = self.margin_top {
                properties.push(("margin-top", margin_top));
            }
if let Some(ref name) = self.name {
                properties.push(("name", name));
            }
if let Some(ref no_show_all) = self.no_show_all {
                properties.push(("no-show-all", no_show_all));
            }
        #[cfg(any(feature = "gtk_v3_8", feature = "dox"))]
if let Some(ref opacity) = self.opacity {
                properties.push(("opacity", opacity));
            }
if let Some(ref parent) = self.parent {
                properties.push(("parent", parent));
            }
if let Some(ref receives_default) = self.receives_default {
                properties.push(("receives-default", receives_default));
            }
if let Some(ref sensitive) = self.sensitive {
                properties.push(("sensitive", sensitive));
            }
        #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
if let Some(ref tooltip_markup) = self.tooltip_markup {
                properties.push(("tooltip-markup", tooltip_markup));
            }
        #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
if let Some(ref tooltip_text) = self.tooltip_text {
                properties.push(("tooltip-text", tooltip_text));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref vexpand) = self.vexpand {
                properties.push(("vexpand", vexpand));
            }
        #[cfg(any(feature = "gtk_v3", feature = "dox"))]
if let Some(ref vexpand_set) = self.vexpand_set {
                properties.push(("vexpand-set", vexpand_set));
            }
if let Some(ref visible) = self.visible {
                properties.push(("visible", visible));
            }
if let Some(ref width_request) = self.width_request {
                properties.push(("width-request", width_request));
            }
        glib::Object::new::<Window>(&properties)

    }

    pub fn show_menubar(mut self, show_menubar: bool) -> Self {
        self.show_menubar = Some(show_menubar);
        self
    }

    #[cfg(any(feature = "gtk_v2_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_4")))]
    pub fn accept_focus(mut self, accept_focus: bool) -> Self {
        self.accept_focus = Some(accept_focus);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn application(mut self, application: &impl IsA<gtk::Application>) -> Self {
        self.application = Some(application.clone().upcast());
        self
    }

    #[cfg(any(feature = "gtk_v3_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_4")))]
    pub fn attached_to(mut self, attached_to: &impl IsA<gtk::Widget>) -> Self {
        self.attached_to = Some(attached_to.clone().upcast());
        self
    }

    #[cfg(any(feature = "gtk_v2_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_4")))]
    pub fn decorated(mut self, decorated: bool) -> Self {
        self.decorated = Some(decorated);
        self
    }

    pub fn default_height(mut self, default_height: i32) -> Self {
        self.default_height = Some(default_height);
        self
    }

    pub fn default_width(mut self, default_width: i32) -> Self {
        self.default_width = Some(default_width);
        self
    }

    #[cfg(any(feature = "gtk_v2_10", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_10")))]
    pub fn deletable(mut self, deletable: bool) -> Self {
        self.deletable = Some(deletable);
        self
    }

    pub fn destroy_with_parent(mut self, destroy_with_parent: bool) -> Self {
        self.destroy_with_parent = Some(destroy_with_parent);
        self
    }

    #[cfg(any(feature = "gtk_v2_6", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_6")))]
    pub fn focus_on_map(mut self, focus_on_map: bool) -> Self {
        self.focus_on_map = Some(focus_on_map);
        self
    }

    #[cfg(any(feature = "gtk_v2_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_20")))]
    pub fn focus_visible(mut self, focus_visible: bool) -> Self {
        self.focus_visible = Some(focus_visible);
        self
    }

    #[cfg(any(feature = "gtk_v3_4", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_4")))]
    pub fn hide_titlebar_when_maximized(mut self, hide_titlebar_when_maximized: bool) -> Self {
        self.hide_titlebar_when_maximized = Some(hide_titlebar_when_maximized);
        self
    }

    #[cfg(any(feature = "gtk_v2_6", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_6")))]
    pub fn icon_name(mut self, icon_name: &str) -> Self {
        self.icon_name = Some(icon_name.to_string());
        self
    }

    #[cfg(any(feature = "gtk_v2_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_20")))]
    pub fn mnemonics_visible(mut self, mnemonics_visible: bool) -> Self {
        self.mnemonics_visible = Some(mnemonics_visible);
        self
    }

    pub fn modal(mut self, modal: bool) -> Self {
        self.modal = Some(modal);
        self
    }

    pub fn resizable(mut self, resizable: bool) -> Self {
        self.resizable = Some(resizable);
        self
    }

    pub fn role(mut self, role: &str) -> Self {
        self.role = Some(role.to_string());
        self
    }

    pub fn screen(mut self, screen: &gdk::Screen) -> Self {
        self.screen = Some(screen.clone());
        self
    }

    pub fn skip_pager_hint(mut self, skip_pager_hint: bool) -> Self {
        self.skip_pager_hint = Some(skip_pager_hint);
        self
    }

    pub fn skip_taskbar_hint(mut self, skip_taskbar_hint: bool) -> Self {
        self.skip_taskbar_hint = Some(skip_taskbar_hint);
        self
    }

    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    pub fn startup_id(mut self, startup_id: &str) -> Self {
        self.startup_id = Some(startup_id.to_string());
        self
    }

    pub fn title(mut self, title: &str) -> Self {
        self.title = Some(title.to_string());
        self
    }

    #[cfg(any(feature = "gtk_v2_10", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_10")))]
    pub fn transient_for(mut self, transient_for: &impl IsA<gtk::Window>) -> Self {
        self.transient_for = Some(transient_for.clone().upcast());
        self
    }

    pub fn urgency_hint(mut self, urgency_hint: bool) -> Self {
        self.urgency_hint = Some(urgency_hint);
        self
    }

    pub fn border_width(mut self, border_width: u32) -> Self {
        self.border_width = Some(border_width);
        self
    }

    pub fn child(mut self, child: &impl IsA<gtk::Widget>) -> Self {
        self.child = Some(child.clone().upcast());
        self
    }

    pub fn app_paintable(mut self, app_paintable: bool) -> Self {
        self.app_paintable = Some(app_paintable);
        self
    }

    pub fn can_default(mut self, can_default: bool) -> Self {
        self.can_default = Some(can_default);
        self
    }

    pub fn can_focus(mut self, can_focus: bool) -> Self {
        self.can_focus = Some(can_focus);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn expand(mut self, expand: bool) -> Self {
        self.expand = Some(expand);
        self
    }

    #[cfg(any(feature = "gtk_v3_20", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_20")))]
    pub fn focus_on_click(mut self, focus_on_click: bool) -> Self {
        self.focus_on_click = Some(focus_on_click);
        self
    }

    pub fn has_default(mut self, has_default: bool) -> Self {
        self.has_default = Some(has_default);
        self
    }

    pub fn has_focus(mut self, has_focus: bool) -> Self {
        self.has_focus = Some(has_focus);
        self
    }

    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    pub fn has_tooltip(mut self, has_tooltip: bool) -> Self {
        self.has_tooltip = Some(has_tooltip);
        self
    }

    pub fn height_request(mut self, height_request: i32) -> Self {
        self.height_request = Some(height_request);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn hexpand(mut self, hexpand: bool) -> Self {
        self.hexpand = Some(hexpand);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn hexpand_set(mut self, hexpand_set: bool) -> Self {
        self.hexpand_set = Some(hexpand_set);
        self
    }

    pub fn is_focus(mut self, is_focus: bool) -> Self {
        self.is_focus = Some(is_focus);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn margin(mut self, margin: i32) -> Self {
        self.margin = Some(margin);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn margin_bottom(mut self, margin_bottom: i32) -> Self {
        self.margin_bottom = Some(margin_bottom);
        self
    }

    #[cfg(any(feature = "gtk_v3_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_12")))]
    pub fn margin_end(mut self, margin_end: i32) -> Self {
        self.margin_end = Some(margin_end);
        self
    }

    #[cfg(any(feature = "gtk_v3_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_12")))]
    pub fn margin_start(mut self, margin_start: i32) -> Self {
        self.margin_start = Some(margin_start);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn margin_top(mut self, margin_top: i32) -> Self {
        self.margin_top = Some(margin_top);
        self
    }

    pub fn name(mut self, name: &str) -> Self {
        self.name = Some(name.to_string());
        self
    }

    pub fn no_show_all(mut self, no_show_all: bool) -> Self {
        self.no_show_all = Some(no_show_all);
        self
    }

    #[cfg(any(feature = "gtk_v3_8", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3_8")))]
    pub fn opacity(mut self, opacity: f64) -> Self {
        self.opacity = Some(opacity);
        self
    }

    pub fn parent(mut self, parent: &impl IsA<gtk::Container>) -> Self {
        self.parent = Some(parent.clone().upcast());
        self
    }

    pub fn receives_default(mut self, receives_default: bool) -> Self {
        self.receives_default = Some(receives_default);
        self
    }

    pub fn sensitive(mut self, sensitive: bool) -> Self {
        self.sensitive = Some(sensitive);
        self
    }

    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    pub fn tooltip_markup(mut self, tooltip_markup: &str) -> Self {
        self.tooltip_markup = Some(tooltip_markup.to_string());
        self
    }

    #[cfg(any(feature = "gtk_v2_12", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v2_12")))]
    pub fn tooltip_text(mut self, tooltip_text: &str) -> Self {
        self.tooltip_text = Some(tooltip_text.to_string());
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn vexpand(mut self, vexpand: bool) -> Self {
        self.vexpand = Some(vexpand);
        self
    }

    #[cfg(any(feature = "gtk_v3", feature = "dox"))]
    #[cfg_attr(feature = "dox", doc(cfg(feature = "gtk_v3")))]
    pub fn vexpand_set(mut self, vexpand_set: bool) -> Self {
        self.vexpand_set = Some(vexpand_set);
        self
    }

    pub fn visible(mut self, visible: bool) -> Self {
        self.visible = Some(visible);
        self
    }

    pub fn width_request(mut self, width_request: i32) -> Self {
        self.width_request = Some(width_request);
        self
    }
}

pub trait WindowExt: 'static {
    #[doc(alias = "gedit_window_close_all_tabs")]
    fn close_all_tabs(&self);

    #[doc(alias = "gedit_window_close_tab")]
    fn close_tab(&self, tab: &Tab);

    #[doc(alias = "gedit_window_close_tabs")]
    fn close_tabs(&self, tabs: &[Tab]);

    #[doc(alias = "gedit_window_create_tab")]
    fn create_tab(&self, jump_to: bool) -> Option<Tab>;

    #[doc(alias = "gedit_window_create_tab_from_location")]
    fn create_tab_from_location(&self, location: &impl IsA<gio::File>, encoding: Option<&gtk_source::Encoding>, line_pos: i32, column_pos: i32, create: bool, jump_to: bool) -> Option<Tab>;

    //#[doc(alias = "gedit_window_create_tab_from_stream")]
    //fn create_tab_from_stream(&self, stream: /*Ignored*/&gio::InputStream, encoding: Option<&gtk_source::Encoding>, line_pos: i32, column_pos: i32, jump_to: bool) -> Option<Tab>;

    #[doc(alias = "gedit_window_get_active_document")]
    #[doc(alias = "get_active_document")]
    fn active_document(&self) -> Option<Document>;

    #[doc(alias = "gedit_window_get_active_tab")]
    #[doc(alias = "get_active_tab")]
    fn active_tab(&self) -> Option<Tab>;

    #[doc(alias = "gedit_window_get_active_view")]
    #[doc(alias = "get_active_view")]
    fn active_view(&self) -> Option<View>;

    #[doc(alias = "gedit_window_get_bottom_panel")]
    #[doc(alias = "get_bottom_panel")]
    fn bottom_panel(&self) -> Option<gtk::Widget>;

    #[doc(alias = "gedit_window_get_documents")]
    #[doc(alias = "get_documents")]
    fn documents(&self) -> Vec<Document>;

    //#[doc(alias = "gedit_window_get_group")]
    //#[doc(alias = "get_group")]
    //fn group(&self) -> /*Ignored*/Option<gtk::WindowGroup>;

    #[doc(alias = "gedit_window_get_message_bus")]
    #[doc(alias = "get_message_bus")]
    fn message_bus(&self) -> Option<MessageBus>;

    #[doc(alias = "gedit_window_get_side_panel")]
    #[doc(alias = "get_side_panel")]
    fn side_panel(&self) -> Option<gtk::Widget>;

    #[doc(alias = "gedit_window_get_state")]
    #[doc(alias = "get_state")]
    fn state(&self) -> WindowState;

    #[doc(alias = "gedit_window_get_statusbar")]
    #[doc(alias = "get_statusbar")]
    fn statusbar(&self) -> Option<gtk::Widget>;

    #[doc(alias = "gedit_window_get_tab_from_location")]
    #[doc(alias = "get_tab_from_location")]
    fn tab_from_location(&self, location: &impl IsA<gio::File>) -> Option<Tab>;

    #[doc(alias = "gedit_window_get_unsaved_documents")]
    #[doc(alias = "get_unsaved_documents")]
    fn unsaved_documents(&self) -> Vec<Document>;

    #[doc(alias = "gedit_window_get_views")]
    #[doc(alias = "get_views")]
    fn views(&self) -> Vec<View>;

    #[doc(alias = "gedit_window_set_active_tab")]
    fn set_active_tab(&self, tab: &Tab);

    #[doc(alias = "active-tab-changed")]
    fn connect_active_tab_changed<F: Fn(&Self, &Tab) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "active-tab-state-changed")]
    fn connect_active_tab_state_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "tab-added")]
    fn connect_tab_added<F: Fn(&Self, &Tab) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "tab-removed")]
    fn connect_tab_removed<F: Fn(&Self, &Tab) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "tabs-reordered")]
    fn connect_tabs_reordered<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "state")]
    fn connect_state_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<Window>> WindowExt for O {
    fn close_all_tabs(&self) {
        unsafe {
            ffi::gedit_window_close_all_tabs(self.as_ref().to_glib_none().0);
        }
    }

    fn close_tab(&self, tab: &Tab) {
        unsafe {
            ffi::gedit_window_close_tab(self.as_ref().to_glib_none().0, tab.to_glib_none().0);
        }
    }

    fn close_tabs(&self, tabs: &[Tab]) {
        unsafe {
            ffi::gedit_window_close_tabs(self.as_ref().to_glib_none().0, tabs.to_glib_none().0);
        }
    }

    fn create_tab(&self, jump_to: bool) -> Option<Tab> {
        unsafe {
            from_glib_none(ffi::gedit_window_create_tab(self.as_ref().to_glib_none().0, jump_to.into_glib()))
        }
    }

    fn create_tab_from_location(&self, location: &impl IsA<gio::File>, encoding: Option<&gtk_source::Encoding>, line_pos: i32, column_pos: i32, create: bool, jump_to: bool) -> Option<Tab> {
        unsafe {
            from_glib_none(ffi::gedit_window_create_tab_from_location(self.as_ref().to_glib_none().0, location.as_ref().to_glib_none().0, encoding.to_glib_none().0, line_pos, column_pos, create.into_glib(), jump_to.into_glib()))
        }
    }

    //fn create_tab_from_stream(&self, stream: /*Ignored*/&gio::InputStream, encoding: Option<&gtk_source::Encoding>, line_pos: i32, column_pos: i32, jump_to: bool) -> Option<Tab> {
    //    unsafe { TODO: call ffi:gedit_window_create_tab_from_stream() }
    //}

    fn active_document(&self) -> Option<Document> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_active_document(self.as_ref().to_glib_none().0))
        }
    }

    fn active_tab(&self) -> Option<Tab> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_active_tab(self.as_ref().to_glib_none().0))
        }
    }

    fn active_view(&self) -> Option<View> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_active_view(self.as_ref().to_glib_none().0))
        }
    }

    fn bottom_panel(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_bottom_panel(self.as_ref().to_glib_none().0))
        }
    }

    fn documents(&self) -> Vec<Document> {
        unsafe {
            FromGlibPtrContainer::from_glib_container(ffi::gedit_window_get_documents(self.as_ref().to_glib_none().0))
        }
    }

    //fn group(&self) -> /*Ignored*/Option<gtk::WindowGroup> {
    //    unsafe { TODO: call ffi:gedit_window_get_group() }
    //}

    fn message_bus(&self) -> Option<MessageBus> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_message_bus(self.as_ref().to_glib_none().0))
        }
    }

    fn side_panel(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_side_panel(self.as_ref().to_glib_none().0))
        }
    }

    fn state(&self) -> WindowState {
        unsafe {
            from_glib(ffi::gedit_window_get_state(self.as_ref().to_glib_none().0))
        }
    }

    fn statusbar(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_statusbar(self.as_ref().to_glib_none().0))
        }
    }

    fn tab_from_location(&self, location: &impl IsA<gio::File>) -> Option<Tab> {
        unsafe {
            from_glib_none(ffi::gedit_window_get_tab_from_location(self.as_ref().to_glib_none().0, location.as_ref().to_glib_none().0))
        }
    }

    fn unsaved_documents(&self) -> Vec<Document> {
        unsafe {
            FromGlibPtrContainer::from_glib_container(ffi::gedit_window_get_unsaved_documents(self.as_ref().to_glib_none().0))
        }
    }

    fn views(&self) -> Vec<View> {
        unsafe {
            FromGlibPtrContainer::from_glib_container(ffi::gedit_window_get_views(self.as_ref().to_glib_none().0))
        }
    }

    fn set_active_tab(&self, tab: &Tab) {
        unsafe {
            ffi::gedit_window_set_active_tab(self.as_ref().to_glib_none().0, tab.to_glib_none().0);
        }
    }

    fn connect_active_tab_changed<F: Fn(&Self, &Tab) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn active_tab_changed_trampoline<P: IsA<Window>, F: Fn(&P, &Tab) + 'static>(this: *mut ffi::GeditWindow, object: *mut ffi::GeditTab, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(object))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"active-tab-changed\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(active_tab_changed_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_active_tab_state_changed<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn active_tab_state_changed_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(this: *mut ffi::GeditWindow, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"active-tab-state-changed\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(active_tab_state_changed_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_tab_added<F: Fn(&Self, &Tab) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn tab_added_trampoline<P: IsA<Window>, F: Fn(&P, &Tab) + 'static>(this: *mut ffi::GeditWindow, object: *mut ffi::GeditTab, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(object))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"tab-added\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(tab_added_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_tab_removed<F: Fn(&Self, &Tab) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn tab_removed_trampoline<P: IsA<Window>, F: Fn(&P, &Tab) + 'static>(this: *mut ffi::GeditWindow, object: *mut ffi::GeditTab, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref(), &from_glib_borrow(object))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"tab-removed\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(tab_removed_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_tabs_reordered<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn tabs_reordered_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(this: *mut ffi::GeditWindow, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"tabs-reordered\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(tabs_reordered_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    fn connect_state_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_state_trampoline<P: IsA<Window>, F: Fn(&P) + 'static>(this: *mut ffi::GeditWindow, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Window::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::state\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_state_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl fmt::Display for Window {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Window")
    }
}
